version: 2.1

orbs:
  aws_assume_role: lbh-hackit/aws_assume_role@0.1.0

executors:
  docker-python:
    docker:
      - image: cimg/python:3.12
  docker-terraform:
    docker:
      - image: "hashicorp/terraform:0.12.29"
  docker-dotnet:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:8.0

references:
  workspace_root: &workspace_root "~"
  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

commands:
  assume-role-and-persist-workspace:
    description: "Assumes deployment role and persists credentials across jobs"
    parameters:
      aws-account:
        type: string
    steps:
      - checkout
      - aws_assume_role/assume_role:
          account: <<parameters.aws-account>>
          profile_name: default
          role: "LBH_Circle_CI_Deployment_Role"
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - .aws
  terraform-init-then-destroy:
    description: "Initializes and destroys terraform configuration"
    parameters:
      environment:
        type: string
    steps:
      - *attach_workspace
      - checkout
      - run:
          command: |
            cd ./terraform/<<parameters.environment>>/
            terraform get -update=true
            terraform init
          name: get and init
      - run:
          name: destroy
          command: |
            cd ./terraform/<<parameters.environment>>/
            terraform destroy -auto-approve
  terraform-plan-destroy:
    description: "Initializes and plans terraform destruction"
    parameters:
      environment:
        type: string
    steps:
      - *attach_workspace
      - checkout
      - run:
          command: |
            cd ./terraform/<<parameters.environment>>/
            terraform get -update=true
            terraform init
          name: get and init
      - run:
          name: plan destroy
          command: |
            cd ./terraform/<<parameters.environment>>/
            terraform plan -destroy
  deploy-lambda:
    description: "Deploys API via Serverless"
    parameters:
      stage:
        type: string
    steps:
      - *attach_workspace
      - checkout
      - setup_remote_docker
      - run:
          name: Install Node.js
          command: |
            curl -sL https://deb.nodesource.com/setup_18.x | bash -
            apt-get update && apt-get install -y nodejs
      - run:
          name: Install serverless CLI
          command: npm i -g serverless
      - run:
          name: Build lambda
          command: |
            cd ./CautionaryAlertsApi/
            chmod +x ./build.sh
            ./build.sh
      - run:
          name: Deploy lambda
          command: |
            cd ./CautionaryAlertsApi/
            sls deploy --stage <<parameters.stage>> --conceal
  remove-lambda:
    description: "Removes API via Serverless"
    parameters:
      stage:
        type: string
    steps:
      - *attach_workspace
      - checkout
      - setup_remote_docker
      - run:
          name: Install Node.js
          command: |
            curl -sL https://deb.nodesource.com/setup_18.x | bash -
            apt-get update && apt-get install -y nodejs
      - run:
          name: Install serverless CLI
          command: npm i -g serverless
      - run:
          name: Remove lambda
          command: |
            cd ./CautionaryAlertsApi/
            sls remove --stage <<parameters.stage>>

jobs:
  assume-role-disaster-recovery:
    executor: docker-python
    steps:
      - assume-role-and-persist-workspace:
          aws-account: $AWS_ACCOUNT_DISASTER_RECOVERY
  terraform-plan-destroy-disaster-recovery:
    executor: docker-terraform
    steps:
      - terraform-plan-destroy:
          environment: "production"
  terraform-init-and-destroy-disaster-recovery:
    executor: docker-terraform
    steps:
      - terraform-init-then-destroy:
          environment: "production"
  remove-lambda-disaster-recovery:
    executor: docker-dotnet
    steps:
      - remove-lambda:
          stage: "production"

workflows:
  check-and-destroy-disaster-recovery:
    jobs:
      - assume-role-disaster-recovery:
          context: api-assume-role-disaster-recovery-context
          filters:
            branches:
              only: disaster-recovery-test
      - terraform-plan-destroy-disaster-recovery:
          requires:
            - assume-role-disaster-recovery
          filters:
            branches:
              only: disaster-recovery-test
      - approve-destruction:
          type: approval
          requires:
            - terraform-plan-destroy-disaster-recovery
          filters:
            branches:
              only: disaster-recovery-test
      - terraform-init-and-destroy-disaster-recovery:
          requires:
            - approve-destruction
          filters:
            branches:
              only: disaster-recovery-test
      - remove-lambda-disaster-recovery:
          context:
            - api-nuget-token-context
            - "Serverless Framework"
          requires:
            - approve-destruction
          filters:
            branches:
              only: disaster-recovery-test

